### ISSUE TITLE
Toujours le contrôleur par défaut

### ISSUE THREAD

**Issue by mogwy714** [peakphp/framework#2]
Salut Frank,
Avec la version 2.22, peak utilise toujours le contrôleur par défaut.
J'ai ajouté un nouveau contrôleur (http://modomaine.com/moncontroleur) mais il n'est jamais appelé. c'est toujours le contrôleur par défaut (index) qui est utilisé.

j'ai fait l'installation via composer.

config:
PHP 5.6.30 (cli) (built: Jan 28 2017 14:24:05)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com
--------------------------------
mysql  Ver 15.1 Distrib 10.1.25-MariaDB, for Linux (x86_64) using readline 5.1
--------------------------------

qu'est-ce qu'il me manque ?

merci

**Comment by 1franck** [comment]
Bonjour Mogwy,

Tout d'abord, l'auto-routing est désactivé par défaut, ce qui veut dire que lorsque tu créer un nouveau controlleur, tu dois aussi ajouter une route dans le fichier config/app.php. Deplus, je te conseille de garder l'auto-routing a off car elle sera éventuellement enlevée car elle peut se montrer problématique dans les grosses applications.

Voici la démarche que j'ai fais ce matin, j'espère que cela pourra t'aider a trouver ton problème:

1. Installer l'app avec composer:
```composer create-project peakphp/peak --prefer-dist```

2. Créer un nouveau controlleur TestController.php dans app/Controllers/:
```
<?php

namespace App\Controllers;

use Peak\Bedrock\Application;
use Peak\Bedrock\Controller\ActionController;

/**
 * Test Controller
 */
class TestController extends ActionController
{

    /**
     * index Action (default controller action)
     */
    public function _index()
    {
    }

}
```

3. Ajouter la nouvelle route pour l'action "index" du controlleur "test" dans le fichier config/app.php, section 'routes':
```
'routes' => [
    'mapage | test/index', // route | controller/action
]
```

4. Créer la vue pour cette action: app/Views/Scripts/test.index.php:
```
<h1>Ma page</h1>
```


Maintenant, lorsque je visite http://site.com/mapage, le controller TestController est appelé avec l'action index et le contenu de test.index.php est affiché


Si c'est la première fois que tu utilises la version 2, il y a eu beaucoup de changement, il se peut que tu te heurtes à plusieurs obstacles. 

Si tu es la personne que je crois être , contacte-moi via courriel ou via fb si tu as d'autres questions. Aussi, il me ferait plaisir de te faire un survol des changements et des bonnes pratiques en personne avec toi afin de t'aider à bien démarrer.
